### ISSUE TITLE
Deck with less than 5 cards causes an error

### ISSUE THREAD

**Issue by EFHIII** [agentx3/balatro-handy-odds-calculator#1]
error:
```
fd9d1056-9d5cd2f85cc62087.js:1 Uncaught RuntimeError: unreachable
```

Simply checking if the deck has less than 5 cards and rejecting it if so would probably be sufficient. Right now, the error breaks the site with the calculate button non-clickable, requiring a page refresh to fix.

**Comment by agentx3** [comment]
Thanks for bringing this to my attention. The issue actually occurs when the deck is below the hand-size. I've added validation to check for that, in addition to prevent locking up the the calculate the button.

**Comment by agentx3** [comment]
Can you confirm the issue is fixed on your end?

**Comment by EFHIII** [comment]
It seems to not be breaking
