### ISSUE TITLE
Incorrectly claiming full house

### ISSUE THREAD

**Issue by EFHIII** [agentx3/balatro-handy-odds-calculator#3]
I'm not sure what the cause is, but in this case, it seems to think a full house is possible when it's not:
![image](https://github.com/agentx3/balatro-handy-odds-calculator/assets/20879009/c311f8f4-498a-43ab-bbb6-8ae2be460222)
Note that the hand size is set to 3 (a full house requires 5 cards)

**Comment by agentx3** [comment]
The three of a kind with matching suits should no longer be detected as a full house. Updated and deployed to website, closing for now.
